### ISSUE TITLE
No files found on flash drive  working with horizon

### ISSUE THREAD

**Issue by Shadowkaisa** [ELREVENGE/HaloMCCPCSaveTransferTool#9]
So i followed with the issue No files found on flash drive #8

i transfered my halo 3 and reach both over to a 16gb flashdrive
the xbox 360 file is 14 gb

XTAF creates a content folder in the directory with the xbox 360 folders 

the debug of your folder generates the following in the log

Failed to get current version number from: System.Deployment.Application.ApplicationDeployment.CurrentDeployment.CurrentVersion update check aborted (If the application was not installed with the setup.exe this message is normal.)
Updating Export tab lists
0 Maps, 0 Gametypes, and 0 Screenshots for Halo: Reach
0 Maps, 0 Gametypes, and 0 Screenshots for Halo 3
0 Screenshots for Halo 3: ODST
0 Maps, 0 Gametypes, and 0 Screenshots for Halo 4
All files in Export tab listed!
Updating Manage tab file lists
All files in Manage tab listed!
Updating from folder F:\
Debugging Enabled
Gathering Files
All files Gathered, scanning 18 for potential containers
Potential Container letter check failed first 3 characters are (��) of file:F:\Xbox360\Data0000
Potential Container letter check failed first 3 characters are (XTA) of file:F:\Xbox360\Data0001
Potential Container letter check failed first 3 characters are (C) of file:F:\Xbox360\Data0002
Potential Container letter check failed first 3 characters are (n�) of file:F:\Xbox360\Data0003
Potential Container letter check failed first 3 characters are (�;�) of file:F:\Xbox360\Data0004
Potential Container letter check failed first 3 characters are (P�) of file:F:\Xbox360\Data0005
Potential Container letter check failed first 3 characters are (u!h) of file:F:\Xbox360\Data0006
Potential Container letter check failed first 3 characters are (��) of file:F:\Xbox360\Data0007
Potential Container letter check failed first 3 characters are (�3,) of file:F:\Xbox360\Data0008
Potential Container letter check failed first 3 characters are (~|) of file:F:\Xbox360\Data0009
Potential Container letter check failed first 3 characters are (7om) of file:F:\Xbox360\Data0010
Potential Container letter check failed first 3 characters are (�ñE) of file:F:\Xbox360\Data0011
Potential Container letter check failed first 3 characters are (J~) of file:F:\Xbox360\Data0012
Potential Container letter check failed first 3 characters are (C) of file:F:\Xbox360\Data0013
Potential Container letter check failed first 3 characters are (^JG) of file:F:\Xbox360\Data0014
Potential Container letter check failed first 3 characters are ($�) of file:F:\Xbox360\Data0015
Potential Container letter check failed first 3 characters are (Potential Container letter check failed first 3 characters are ({All Potential Containers Gathered, 0 Gathering Container Info from containers
All Container Files gathered:0
Searching for Halo: Reach files
Searching for Halo 3 files
Searching for Halo 3 ODST files
Searching for Halo 4 files
Updating Export tab lists
0 Maps, 0 Gametypes, and 0 Screenshots for Halo: Reach
0 Maps, 0 Gametypes, and 0 Screenshots for Halo 3
0 Screenshots for Halo 3: ODST
0 Maps, 0 Gametypes, and 0 Screenshots for Halo 4
All files in Export tab listed!

And the FATX tool log is as follows

FATX-Tools v0.3
--------------------------------
Mounting Xbox 360 Retail HDD..
Attempting to load FATX volume at 0000000130EB0000
Failed to mount Partition1: Invalid FATX Signature for Partition1: BD3D756F
Attempting to load FATX volume at 0000000120EB0000
Failed to mount SystemPartition: Invalid FATX Signature for SystemPartition: 9CFCCCE6
Attempting to load FATX volume at 0000000118EB0000
Failed to mount SystemAuxPartition: Invalid FATX Signature for SystemAuxPartition: EBA1848E

**Comment by ELREVENGE** [comment]
From the following parts of your comment and the log 
> i transfered my halo 3 and reach both over to a 16gb flashdrive
the xbox 360 file is 14 gb

>Potential Container letter check failed first 3 characters are (���) of file:F:\Xbox360\Data0000
>Potential Container letter check failed first 3 characters are (XTA) of file:F:\Xbox360\Data0001
>Potential Container letter check failed first 3 characters are (��C) of file:F:\Xbox360\Data0002

It appears your drive is formatted in the same way the drive in issue #8 was. I'm guessing you and them transferred the whole title instead of selecting just the content (maps, gamemodes, etc) from the titles. I think the person in issue #8 had done a similar thing. **I'm guessing** that transferring the title changes how the xbox formats the data compared to selecting individual files. If you ran this tool [XTAF limited multithreading.zip](https://github.com/ELREVENGE/HaloMCCPCSaveTransferTool/files/7722574/XTAF.limited.multithreading.zip) from [the comment I posted in issue 8](https://github.com/ELREVENGE/HaloMCCPCSaveTransferTool/issues/8#issuecomment-995201745) I'm guessing it would produce an output similar to the one produced in issue #8. 

It essentially boils down to my tool looking for files formatted differently. When I was initially developing this tool the files I was working with were formatted like `D:\Content\Profile ID Here\Title ID Here\00000001\usermap000000004C2D7BE4A` not files formatted like `D:\Xbox360\Data0033` aside from the name and location **the internals of the files are very different**. 

I had originally wanted to work on adding support for that kind of format but, with the job and other commitments I have now I don't have as much time to work on some of my passion projects like this. I'm still willing to look into a workaround or solution to implement into the tool but, without the whole set of Data files it won't be easy to test potential solutions on my own (if you want to upload the files I can try to use them to test pulling useable game files from these but I'm guessing it's a big upload). If you have files on there that you really want you could look into another tool like horizon. (Simply because as far as I know there's no way to mass export files from horizon you would have to manually save each file which _is doable_ but **very time consuming**. I think that might be faster than I could develop a solution with my free time lately anyway.

The only **potential workaround** I can think of right now would be to (backup just in case then) transfer the files back to the 360. Then select files to move from the titles instead of moving the whole title. (assuming that's the root cause as to why your files are formatted the way they are)

**Comment by Shadowkaisa** [comment]
It is about 14-20gb off memory, i pulled halo 3 - halo reaches files from the xbox excluding the DLC folders.

I can upload it all this weekend as I no longer have easy access to the xbox as it was a whim when i was at my parents.

Do you have any suggestions on where would be the best place to upload?

**Comment by ELREVENGE** [comment]
>It is about 14-20gb off memory
...
Do you have any suggestions on where would be the best place to upload?

I would normally suggest Google drive since most people already have an account and it's easy to find examples of how to upload and share a file/folder. In this case however the 14-20GB of files would be more space than the free plan has available (15GB for free then they charge monthly/yearly for additional space). When I was looking into various sites that might work I found the free plan info for [mega.io](https://mega.io/). It looks like you get 20GB of space on the free plan. I've only downloaded from mega, I've never personally uploaded so I'm not sure on the specifics of how to upload.

**Comment by Shadowkaisa** [comment]
Here is the entire xbox 360 folder on mega
https://mega.nz/folder/OW5zDSCC#SzeDD2969P8CzeeWil1CnQ

**Comment by ELREVENGE** [comment]
Great news, I've got your files ready for MCC PC. I was looking more into it. [The way the Xbox 360 saved files onto USBs changed after a certain update.](https://gruntmods.com/usb-xtaf-program-obsolete/) The format I wrote my tool for is trying to use the newer format. I used an older tool called [usb-xtaf-explorer from gruntmods.com](https://gruntmods.com/usb-xtaf-explorer/) to extract the content folder from the files you uploaded. After that my tool was able to read them from the extracted content folder just fine.
![image](https://github.com/ELREVENGE/HaloMCCPCSaveTransferTool/assets/2909708/eb2977b8-57f9-436f-b488-6a6356498886)
I went ahead and extracted all the files it found to save you some time. 

- 29 Maps and 15 Gametypes for Halo: Reach
- 67 Maps and 31 Gametypes for Halo 3

[MCC PC ready content.zip](https://github.com/ELREVENGE/HaloMCCPCSaveTransferTool/files/15301436/MCC.PC.ready.content.zip)
**Let me know if the files above work for you or not. If all is well and they work in game for you please leave another comment so I can close the issue.** 
If those are all the files you expected and everything works feel free to delete the mega upload if you would like (not sure exactly what info someone could pull from the files but I do know your Xbox ID is stored on there (why I blocked out some of the screenshot) I have a local copy for testing purposes so there's no need to store them online anymore.

Thank you so much for uploading the whole set of data files, I finally have something I can use to test against for implementing the ability to read from the format you have! I may even be able to help the user in issue #8 get their problem solved now that I know what tool works for reading this kind of data.

**Comment by Shadowkaisa** [comment]
They all seem to work perfectly thank you so much! I appreciate you doing all this work
